### ISSUE TITLE
README file should contain more information

### ISSUE THREAD

**Issue by lochnesh** [ankurshrivastava11/DwollaWeatherApp#1]
The README file for this repository is not very informative.

Can you please update it to
- Provide a description of the project
- Provide information how to build and run this application
- With a badge that displays the results and links to the [Travis CI build](https://docs.travis-ci.com/user/status-images/)

**Comment by ankurshrivastava11** [comment]
The README file has been updated.

It consists the information on how to build and run the application using both the interfaces.
It consists the results and links to the Travis CI Build.
