### ISSUE TITLE
Application exposes APPID

### ISSUE THREAD

**Issue by lochnesh** [ankurshrivastava11/DwollaWeatherApp#2]
This application exposes (via public source control) the APPID which should be secret for this application.  The ID is exposed [here](https://github.com/ankurshrivastava11/DwollaWeatherApp/blob/master/src/org/dwolla/Weather.java#L48).  Please update the application so that APPID is not available in source control.

**Comment by ankurshrivastava11** [comment]
The API Key used in this application has been secured and hidden from the source control. The API Key has been stored in the properties file. In future, this property file can be stored on the server and the key can be referenced from the path to the server where this file is stored. I have included the property file in this repository so as to access and display the result of this application without using the server.
