### ISSUE TITLE
Provide an interface to run this application from the command line

### ISSUE THREAD

**Issue by lochnesh** [ankurshrivastava11/DwollaWeatherApp#4]
The HTML interface for interacting with this application is functional, but it requires the user to install a servlet container.  Please provide a way for a user to run this application from the command line in addition to running the HTML interface.

**Comment by ankurshrivastava11** [comment]
An interface to run this application from the command line in addition to running the HTML interface has been provided in the application. README file contains the information on how to run it using command line.
